interactions:
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"sku":{"name":"Standard_D8s_v3","tier":"GeneralPurpose","capacity":8},"properties":{"fullyQualifiedDomainName":"azuredbclitest-000002.postgres.database.azure.com","version":"12","standbyCount":0,"haEnabled":"Disabled","administratorLogin":"eagerRaccoon1","publicNetworkAccess":"Disabled","delegatedSubnetArguments":{"subnetArmResourceId":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Network/virtualNetworks/VNETbclitest-0225-vnetservermgmtscenar/subnets/Subnetbclitest-0225-vnetservermgmtscenar"},"logBackupStorageSku":"Standard_ZRS","haState":"NotEnabled","state":"Ready","availabilityZone":"1","storageProfile":{"storageMB":131072,"backupRetentionDays":7},"earliestRestoreDate":"2021-02-25T09:15:47.5032374+00:00","byokEnforcement":"Disabled","maintenanceWindow":{"customWindow":"Disabled","dayOfWeek":0,"startHour":0,"startMinute":0}},"location":"East
        US 2 EUAP","id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBforPostgreSQL/flexibleServers/azuredbclitest-000002","name":"azuredbclitest-000002","type":"Microsoft.DBforPostgreSQL/flexibleServers"}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '1279'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:15:46 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      transfer-encoding:
      - chunked
      vary:
      - Accept-Encoding
      x-content-type-options:
      - nosniff
    status:
      code: 200
      message: OK
- request:
    body: '{"location": "East US 2 EUAP", "properties": {"sourceServerName": "azuredbclitest-000002",
      "pointInTimeUTC": "2021-02-25T08:55:47.100007Z", "availabilityZone": "2", "createMode":
      "PointInTimeRestore"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      Content-Length:
      - '220'
      Content-Type:
      - application/json; charset=utf-8
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/restore-azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"error":{"code":"InternalServerError","message":"An unexpected error
        occured while processing the request. Tracking ID: ''2d2101ad-f455-43b4-a868-5804ff3b9f28''"}}'
    headers:
      cache-control:
      - no-cache
      connection:
      - close
      content-length:
      - '162'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:15:48 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - service
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"location": "East US 2 EUAP", "properties": {"sourceServerName": "azuredbclitest-000002",
      "pointInTimeUTC": "2021-02-25T08:55:47.100007Z", "availabilityZone": "2", "createMode":
      "PointInTimeRestore"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      Content-Length:
      - '220'
      Content-Type:
      - application/json; charset=utf-8
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/restore-azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"error":{"code":"InternalServerError","message":"An unexpected error
        occured while processing the request. Tracking ID: ''99447fdb-bf73-4859-8bdf-930a406d892a''"}}'
    headers:
      cache-control:
      - no-cache
      connection:
      - close
      content-length:
      - '162'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:15:49 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - service
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"location": "East US 2 EUAP", "properties": {"sourceServerName": "azuredbclitest-000002",
      "pointInTimeUTC": "2021-02-25T08:55:47.100007Z", "availabilityZone": "2", "createMode":
      "PointInTimeRestore"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      Content-Length:
      - '220'
      Content-Type:
      - application/json; charset=utf-8
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/restore-azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"error":{"code":"InternalServerError","message":"An unexpected error
        occured while processing the request. Tracking ID: ''f57e35da-c399-4364-a6ca-63a28cadd686''"}}'
    headers:
      cache-control:
      - no-cache
      connection:
      - close
      content-length:
      - '162'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:15:52 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - service
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"location": "East US 2 EUAP", "properties": {"sourceServerName": "azuredbclitest-000002",
      "pointInTimeUTC": "2021-02-25T08:55:47.100007Z", "availabilityZone": "2", "createMode":
      "PointInTimeRestore"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      Content-Length:
      - '220'
      Content-Type:
      - application/json; charset=utf-8
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/restore-azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"error":{"code":"InternalServerError","message":"An unexpected error
        occured while processing the request. Tracking ID: ''9d1112da-8ba7-4e2b-a9cf-6d30178999f0''"}}'
    headers:
      cache-control:
      - no-cache
      connection:
      - close
      content-length:
      - '162'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:15:57 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - service
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"location": "East US 2 EUAP", "properties": {"sourceServerName": "azuredbclitest-000002",
      "pointInTimeUTC": "2021-02-25T08:55:47.100007Z", "availabilityZone": "2", "createMode":
      "PointInTimeRestore"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - postgres flexible-server restore
      Connection:
      - keep-alive
      Content-Length:
      - '220'
      Content-Type:
      - application/json; charset=utf-8
      ParameterSetName:
      - -g --name --source-server --restore-time --zone
      User-Agent:
      - python/3.7.7 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3
        azure-mgmt-rdbms/2020-02-14-privatepreview Azure-SDK-For-Python AZURECLI/2.19.1
      accept-language:
      - en-US
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.DBForPostgreSql/flexibleServers/restore-azuredbclitest-000002?api-version=2020-02-14-preview
  response:
    body:
      string: '{"error":{"code":"InternalServerError","message":"An unexpected error
        occured while processing the request. Tracking ID: ''3a56cd06-379b-4e4b-bea6-c6bc5e99c07f''"}}'
    headers:
      cache-control:
      - no-cache
      connection:
      - close
      content-length:
      - '162'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 25 Feb 2021 09:16:04 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - service
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
    status:
      code: 500
      message: Internal Server Error
version: 1
